---
title: Cleanup
description: Cleans up most of the remaining things
privilege: TrustedInstaller
actions:
  # TrustedInstaller Mode lol
 - !writeStatus: {status: 'Cleaning up'}
   # Xbox cleanup
# Nope
# - !file: {path: '%ProgramFiles%\WindowsApps\Microsoft.GamingApp*', option: 'amelioration'}
# - !file: {path: '%ProgramFiles%\WindowsApps\Microsoft.XboxGameCallableUI*', option: 'amelioration'}
# - !file: {path: '%ProgramFiles%\WindowsApps\Microsoft.XboxGamingOverlay*', option: 'amelioration'}
# - !file: {path: '%ProgramFiles%\WindowsApps\Microsoft.XboxSpeechToTextOverlay*', option: 'amelioration'}
# - !file: {path: '%ProgramFiles%\WindowsApps\Microsoft.Xbox.TCUI*', option: 'amelioration'}
# - !service {name: 'XboxGipSvc', operation: delete, option: 'amelioration'}
# - !service {name: 'XboxNetApiSvc', operation: delete, option: 'amelioration'}
# - !service {name: 'XblAuthManager', operation: delete, option: 'amelioration'}
# - !service {name: 'XblGameSave', operation: delete, option: amelioration'}
# - !service {name: 'BcastDVRUserService*', operation: delete, option: 'amelioration'}
   # Edge cleanup
 - !file: {path: '%ProgramFiles%\WindowsApps\Microsoft.MicrosoftEdge*', option: 'remove-edge'}
   # Ink cleanup
 - !file: {path: '%ProgramFiles%\WindowsApps\Microsoft.Ink*'}
 - !file: {path: '%ProgramFiles%\Common Files\microsoft shared\ink\TabTip.exe'} # Required for Win10
   # Scheduled tasks
 - !scheduledTask: {path: "\\Microsoft\\Windows\\Customer Experience Improvement Program\\Consolidator", operation: delete}
 - !scheduledTask: {path: "\\Microsoft\\Windows\\Customer Experience Improvement Program\\KernelCeipTask", operation: delete}
 - !scheduledTask: {path: "\\Microsoft\\Windows\\Customer Experience Improvement Program\\UsbCeip", operation: delete}
 - !scheduledTask: {path: "\\Microsoft\\Windows\\Application Experience\\ProgramDataUpdater", operation: delete}
 - !scheduledTask: {path: "\\Microsoft\\Windows\\Application Experience\\StartupAppTask", operation: delete}
 - !scheduledTask: {path: "\\Microsoft\\Windows\\HelloFace\\FODCleanupTask", operation: delete}
 - !scheduledTask: {path: "\\Microsoft\\Windows\\Maps\\MapsToastTask", operation: delete}
 - !scheduledTask: {path: "\\Microsoft\\Windows\\Maps\\MapsUpdateTask", operation: delete}
 - !scheduledTask: {path: "\\OneDrive*", operation: delete}
   # Windows Mail
 - !file: {path: '%programfiles%\Windows Mail'}
 - !file: {path: '%programfiles(x86)%\Windows Mail'}